GUI Undo and Redo
mucsci-students/2020fa-420-mike pull request #190
Opened 2020-11-19 01:19 UTC by HomelessSkittle

## Proposed Changes
Make undo and redo work in the GUI
  
## Types of Changes
- [ ] Bugfix (Change to a current feature to improve functionality or prevent some issue)
- [x] New feature (Brand new functionality that you want added to the codebase)
- [ ] Other (Anything that doesn't quite fit the above criteria)

## Further Comments
https://www.youtube.com/watch?v=97fQoffpJiM

2020-11-19 15:31 UTC, SerbianSensation requested changes
Bug: Creating a relationship a->b, hitting undo, then redo, then enabling edit mode and clicking class a crashes the program.
Output from Bug:
at mike.view.GUIView.resetLinesFromConversion(GUIView.java:209)
        at mike.view.GUIView.htmlBoxToEditBox(GUIView.java:183)
        at mike.controller.ClassController$3.mousePressed(ClassController.java:76)

Inconvenient thing: When first adding a relationship, parameter, or field, then saving and exiting edit mode, I have to click undo twice for it to do something.

Other than that, looks really good so far!

2020-11-19 19:46 UTC, SerbianSensation reviewed
Tested it again and it seems to work great, excellent work! Couldn't find anything wrong.

Now onto tests...

2020-11-22 01:16 UTC, JohnHynes submitted a review, later dismissed

2020-11-22 02:14 UTC, SerbianSensation approved these changes
Really good job getting the GUI tests to ( finally ) work on GitHub! We can finally test that stuff and increase the code coverage haha. Looks good to me!

2020-11-22 02:17 UTC, merged