Feature/cli
mucsci-students/2020fa-420-mike pull request #25
Opened 2020-09-17 21:36 UTC by HomelessSkittle

CLI should be updated to now work with fields and methods. Output also slightly changed to reflect this.

Contains changes made to Classes.java to prevent multiple relationships between classes
Also contains all tests merged to develop as of 9/17/20

2020-09-17 21:45 UTC, HomelessSkittle commented
As a heads-up/warning/PSA/to whom it may concern:

There were a lot of conflicts that couldn't be resolved (The 'there's a one line difference but github can't figure out what", problem) and I fixed it up to remove those issues. 

This unfortunately makes it look like a lot of things were changed in files that don't actually get touched at all like Classes.java or Relationships.java.

2020-09-17 22:34 UTC, SerbianSensation requested changes
Command Line part looks good, but there are some missing/extra curly braces in the datastructures/testcases files. Don't want the program to crash because of those annoying little things! ;)

2020-09-17 22:34 UTC, SerbianSensation commented on src/datastructures/Classes.java
> +}
Added an extra curly brace at the end.

2020-09-17 22:34 UTC, SerbianSensation commented on src/testcases/RelationshipTest.java
> -}
Missing a curly brace to close the Class.

2020-09-17 22:34 UTC, SerbianSensation commented on src/datastructures/Relationship.java
> -}
Missing a curly brace to close the Class.

2020-09-17 22:34 UTC, SerbianSensation commented on src/testcases/EntityTest.java
> +
Missing a curly brace to close the Class.

2020-09-17 23:09 UTC, JohnHynes requested changes
Looks good, a couple of small things I found but otherwise, it's looking pretty finished.

2020-09-17 23:09 UTC, JohnHynes commented on src/testcases/ClassesTest.java
> -        classes.clear()
Missing ;

2020-09-17 23:09 UTC, JohnHynes commented on src/testcases/ClassesTest.java
> -        assertFalse("Old e1_copy no longer equal to E1", classes.getEntities().get(0).equals(e1copy))
Missing ;

2020-09-17 23:09 UTC, JohnHynes commented on src/cli/CommandLine.java
> +							System.out.println(errorMessage + commandUsage[113] + "\n");
13 instead of 113?

2020-09-17 23:29 UTC, HomelessSkittle commented on src/testcases/ClassesTest.java
> -        classes.clear()
Fixed

2020-09-17 23:29 UTC, HomelessSkittle commented on src/testcases/ClassesTest.java
> -        assertFalse("Old e1_copy no longer equal to E1", classes.getEntities().get(0).equals(e1copy))
Fixed

2020-09-17 23:29 UTC, HomelessSkittle commented on src/cli/CommandLine.java
> +							System.out.println(errorMessage + commandUsage[113] + "\n");
Fixed

2020-09-18 13:06 UTC, JohnHynes approved these changes
I haven't found anything else, looks good!

2020-09-18 16:39 UTC, SerbianSensation approved these changes
Looks good to me. Good job fixing the curly braces, and the hard to spot missing semicolon. I like the way you set up the command usage messages, the indexes are easy to follow since they are in order down the CLI and can be re-used in the help messages. Very nice.

2020-09-18 16:39 UTC, merged